<?php
require_once('../private_html/config.php');
$Template = vlobby\getTemplate('DEFAULT');
$Template->setPageTitle('Privacy Policy');
$Template->setPageContent('<div class="vlobby-contents">
                            <h2 class="text-center font-PoiretOne nomargin"><a href="'.\vlobby\THIS_DOMAIN.'">Vlobby</a> > Privacy Policy</h2>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">This privacy policy has been compiled to better serve those who are concerned with how their &#39;Personally identifiable information&#39; (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>What personal information do we collect from the people that visit our blog, website or app?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">When logging in our site, as appropriate, your public information from STEAM will be automaticly be collected and/or other details to help you with your experience.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>When do we collect information?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We collect information from you only when you log in to our website ("Sign in through STEAM") or enter information on our site.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>How do we use your information?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We may use the information we collect from you when you register, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• To personalize user&#39;s experience and to allow us to deliver the type of content and product offerings in which you are most interested.</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• To improve our website in order to better serve you.</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• To administer a contest, promotion, survey or other site feature.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>How do we protect visitor information?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We do not use vulnerability scanning and/or scanning to PCI standards.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We use regular Malware Scanning.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We do not use an SSL certificate and We do not need an SSL because:</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We only collect public information from STEAM. We do NOT collect any sensitive information.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>Do we use &#39;cookies&#39;?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Yes. Cookies are small files that a site or its service provider transfers to your computer&#39;s hard drive through your Web browser (if you allow) that enables the site&#39;s or service provider&#39;s systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>We use cookies to:</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• Understand and save user&#39;s preferences for future visits.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser&#39;s Help menu to learn the correct way to modify your cookies.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>If users disable cookies in their browser:</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">If you disable cookies off, some features will be disabled. It will turn off some of the features that make your site experience more efficient and some of our services will not function properly, like any feature that requires you to be logged in.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>Third Party Disclosure</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide you with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others&#39; rights, property, or safety.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Third party links</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>Google</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Google&#39;s advertising requirements can be summed up by Google&#39;s Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We use Google AdSense Advertising on our website.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Google, as a third party vendor, uses cookies to serve ads on our site. Google&#39;s use of the DART cookie enables it to serve ads to our users based on their visit to our site and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>We have implemented the following:</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• Remarketing with Google AdSense</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We along with third-party vendors, such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions, and other ad service functions as they relate to our website.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Opting out:</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising initiative opt out page or permanently using the Google Analytics Opt Out Browser add on.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>California Online Privacy Protection Act</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law&#39;s reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>According to CalOPPA we agree to the following:</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• Users can visit our site anonymously</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• Once this privacy policy is created, we will add a link to it on our home page, or as a minimum on the first significant page after entering our website.</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• Our Privacy Policy link includes the word &#39;Privacy&#39;, and can be easily be found on the page specified above.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Users will be notified of any privacy policy changes:</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• On our Privacy Policy Page & via website-notification</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Users are able to change their personal information:</h4>
                            <h4 class="font-PoiretOne padding-top-20 padding-left-10 nomargin">• By logging in to their STEAM account</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>How does our site handle do not track signals?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>Does our site allow third party behavioral tracking?</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">It&#39;s also important to note that we allow third party behavioral tracking</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>COPPA (Children Online Privacy Protection Act)</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">When it comes to the collection of personal information from children under 13, the Children&#39;s Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation&#39;s consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children&#39;s privacy and safety online.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We do not specifically market to children under 13.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>Fair Information Practices</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We will notify the users via in site notification within 7 businees days after finding out about the data breach.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">We also agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>CAN SPAM Act</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>To be accordance with CANSPAM we agree to the following:</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">If at any time you would like to unsubscribe from receiving future emails, you can and we will promptly remove you from ALL correspondence.</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin"><strong>Contacting Us</strong></h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">If there are any questions regarding this privacy policy you may contact us using the information below.</h4>
                            <h4 class="font-PoiretOne nomargin">http://vlobby.net</h4>
                            <h4 class="font-PoiretOne nomargin">Salonika</h4>
                            <h4 class="font-PoiretOne nomargin">Greece</h4>
                            <h4 class="font-PoiretOne nomargin">Mhtr.Xrys.25</h4>
                            <h4 class="font-PoiretOne nomargin">Panorama</h4>
                            <h4 class="font-PoiretOne nomargin">55236</h4>
                            <h4 class="font-PoiretOne nomargin">vlobby@</h4>
                            <h4 class="font-PoiretOne padding-top-20 nomargin">Last Edited on 2014-12-24</h4>
                           </div>');
$Template->designTemplate();
?>